### ISSUE TITLE
sim_model.blend Doesn't Render Scene Correctly

### ISSUE THREAD

**Issue by rainwaffles** [avbotz/marlin#2]
I'm not well-versed in blender, so I don't know how the water background in the .blend file works. Right now the front and down camera show completely black backgrounds and the objects in the scene show up as rainbow-colored disco balls.

Pls help.

**Comment by varun-magesh** [comment]
I'll look at this at home today (blender is too slow on my laptop).

**Comment by varun-magesh** [comment]
Not reproducible. I'm not sure if you realize this, but it will only render what the camera is touching. The bounds of the camera represent the camera's field of view exactly: if you want an object to be seen it needs to be inside or on that little pyramid.

BAD:
![image](https://cloud.githubusercontent.com/assets/7690541/16060732/233e9cae-323e-11e6-971f-44d55ac05ec6.png)

output: blue screen

GOOD:
![image](https://cloud.githubusercontent.com/assets/7690541/16060697/fa8e44da-323d-11e6-9ef4-bbb9e8eb6769.png)

output: 
![0001](https://cloud.githubusercontent.com/assets/7690541/16060788/608bdc2a-323e-11e6-8d3c-c804d4113bd6.png)

**Comment by varun-magesh** [comment]
Rainbow colored disco balls: not reproducible. What I _can_ tell you is to make sure that 
![texture](https://cloud.githubusercontent.com/assets/7690541/16060904/ffe79dcc-323e-11e6-970d-f7c03a60a077.png) this option box shows the little red and white checkers or the 'texture' option.
